version: '3'

services:

  jupyter-server:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ${PWD}/Data:/work_dir/DA
    ports:
      - "8888:8888"